<?php

return [
    'prefixes' =>
        [
            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
            'oslc' => 'http://open-services.net/ns/core#',
        ],
    'oslc:responseInfo' =>
        [
            'oslc:nextPage' =>
                [
                    'rdf:resource' => 'http://localhost/maximo/oslc/os/mxperson/?pageno=2&oslc.pageSize=5&oslc.select=*',
                ],
            'pagenum' => 1,
            'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/?oslc.select=*&oslc.pageSize=5',
        ],
    'rdfs:member' =>
        [
            0 =>
                [
                    'spi:nrcontractcomp' => 'NR',
                    'spi:wfmailelection_description' => 'Notify based on the process',
                    'spi:plusgsolnapprover' => false,
                    '_rowstamp' => '2860813227',
                    'spi:firstname' => 'Oscar',
                    'spi:plusgtechauthority' => false,
                    'spi:city' => 'Milton Keynes',
                    'spi:primaryphone' => '01908 956764',
                    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--/sms',
                    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--/email',
                    'spi:plusgauditapprover' => false,
                    'spi:plusgptwissuecounter' => 0,
                    'spi:phone' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3211929',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--/phone/0-78',
                                    'spi:phonenum' => '01908 956764',
                                    'spi:phoneid' => 78,
                                    'rdf:about' => 'http://childkey#UEVSU09OL1BIT05FL09ZQU0vMDE5MDggOTU2NzY0L35OVUxMfg--',
                                ],
                        ],
                    'spi:lastname' => 'Yam',
                    'spi:email' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3211936',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--/email/0-40',
                                    'spi:emailaddress' => 'oscar.yam@networkrail.co.uk',
                                    'spi:emailid' => 40,
                                    'rdf:about' => 'http://childkey#UEVSU09OL0VNQUlML29zY2FyLnlhbUBuZXR3b3JrcmFpbC5jby51aw--',
                                ],
                        ],
                    'spi:language' => 'EN',
                    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--/phone',
                    'spi:loctoservreq' => true,
                    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/_T1lBTQ--',
                    'spi:displayname' => 'Oscar Yam',
                    'spi:title' => 'Mr',
                    'spi:stateprovince' => 'Buckinghamshire',
                    'spi:locale_description' => 'English (United Kingdom)',
                    'spi:status_description' => 'Inactive',
                    'spi:statusiface' => false,
                    'spi:status' => 'INACTIVE',
                    'spi:country' => 'England',
                    'spi:driverpoints' => 0,
                    'spi:authtodrive' => false,
                    'spi:transemailelection' => 'NEVER',
                    'spi:addressline1' => '500 Station House, Elder Gate',
                    'spi:plusgmocrevapp' => false,
                    'spi:department' => 'NDS Business Systems',
                    'spi:plusgfinauthority' => false,
                    'spi:driverarchived' => false,
                    'spi:postalcode' => 'MK9 1BB',
                    'spi:personid' => 'OYAM',
                    'spi:wfmailelection' => 'PROCESS',
                    'spi:plusgperissueauth' => false,
                    'spi:plusgperperfauth' => false,
                    'spi:statusdate' => '2018-07-12T07:15:21+01:00',
                    'spi:transemailelection_description' => 'Never Notify',
                    'spi:locale' => 'en_GB',
                    'spi:plusgrcfaapprover' => false,
                    'spi:plusgisospec' => false,
                    'spi:personuid' => 296,
                    'spi:plusgperareaauth' => false,
                    'spi:plusgiscertified' => false,
                    'spi:acceptingwfmail' => true,
                    'spi:primaryemail' => 'oscar.yam@networkrail.co.uk',
                ],
            1 =>
                [
                    'spi:nrcontractcomp' => 'NR',
                    'spi:wfmailelection_description' => 'Notify based on the process',
                    'spi:plusgsolnapprover' => false,
                    '_rowstamp' => '2860813228',
                    'spi:firstname' => 'Jason',
                    'spi:plusgtechauthority' => false,
                    'spi:city' => 'London',
                    'spi:primaryphone' => '07824410563',
                    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ/sms',
                    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ/email',
                    'spi:plusgauditapprover' => false,
                    'spi:plusgptwissuecounter' => 0,
                    'spi:phone' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3210890',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ/phone/0-62',
                                    'spi:phonenum' => '07824410563',
                                    'spi:phoneid' => 62,
                                    'rdf:about' => 'http://childkey#UEVSU09OL1BIT05FL0pEQVJDWS8wNzgyNDQxMDU2My9_TlVMTH4-',
                                ],
                        ],
                    'spi:lastname' => 'D\'Arcy',
                    'spi:email' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3210889',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ/email/0-24',
                                    'spi:emailaddress' => 'Jason.DArcy@networkrail.co.uk',
                                    'spi:emailid' => 24,
                                    'rdf:about' => 'http://childkey#UEVSU09OL0VNQUlML0phc29uLkRBcmN5QG5ldHdvcmtyYWlsLmNvLnVr',
                                ],
                        ],
                    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ/phone',
                    'spi:loctoservreq' => true,
                    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/_SkRBUkNZ',
                    'spi:displayname' => 'Jason D\'Arcy',
                    'spi:title' => 'MR',
                    'spi:stateprovince' => 'Greater London',
                    'spi:locale_description' => 'English (United Kingdom)',
                    'spi:status_description' => 'Inactive',
                    'spi:statusiface' => false,
                    'spi:status' => 'INACTIVE',
                    'spi:country' => 'England',
                    'spi:locationorg' => 'NR',
                    'spi:driverpoints' => 0,
                    'spi:authtodrive' => false,
                    'spi:transemailelection' => 'NEVER',
                    'spi:addressline1' => '355 Euston Road',
                    'spi:plusgmocrevapp' => false,
                    'spi:locationsite' => 'NRFAMS',
                    'spi:department' => 'IM London',
                    'spi:plusgfinauthority' => false,
                    'spi:driverarchived' => false,
                    'spi:postalcode' => 'NW1 3AL',
                    'spi:personid' => 'JDARCY',
                    'spi:wfmailelection' => 'PROCESS',
                    'spi:plusgperissueauth' => false,
                    'spi:plusgperperfauth' => false,
                    'spi:statusdate' => '2018-07-12T07:20:36+01:00',
                    'spi:transemailelection_description' => 'Never Notify',
                    'spi:locale' => 'en_GB',
                    'spi:plusgrcfaapprover' => false,
                    'spi:plusgisospec' => false,
                    'spi:personuid' => 250,
                    'spi:plusgperareaauth' => false,
                    'spi:plusgiscertified' => false,
                    'spi:acceptingwfmail' => true,
                    'spi:primaryemail' => 'Jason.DArcy@networkrail.co.uk',
                ],
            2 =>
                [
                    'spi:deviceclass' => 2,
                    'spi:status' => 'ACTIVE',
                    'spi:driverpoints' => 0,
                    'spi:authtodrive' => false,
                    'spi:transemailelection' => 'NEVER',
                    'spi:nrcontractcomp' => 'NR',
                    'spi:plusgmocrevapp' => false,
                    'spi:wfmailelection_description' => 'Notify based on the process',
                    'spi:plusgsolnapprover' => false,
                    'spi:deviceclass_description' => 'Advanced',
                    'spi:plusgfinauthority' => false,
                    '_rowstamp' => '2860813229',
                    'spi:firstname' => 'Max',
                    'spi:plusgtechauthority' => false,
                    'spi:driverarchived' => false,
                    'spi:personid' => 'MAXTEST',
                    'spi:wfmailelection' => 'PROCESS',
                    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TUFYVEVTVA--/sms',
                    'spi:plusgperissueauth' => false,
                    'spi:plusgperperfauth' => false,
                    'spi:statusdate' => '2010-02-08T22:09:36+00:00',
                    'spi:transemailelection_description' => 'Never Notify',
                    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TUFYVEVTVA--/email',
                    'spi:locale' => 'en_GB',
                    'spi:plusgauditapprover' => false,
                    'spi:plusgrcfaapprover' => false,
                    'spi:plusgisospec' => false,
                    'spi:plusgptwissuecounter' => 0,
                    'spi:lastname' => 'Test',
                    'spi:language' => 'EN',
                    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TUFYVEVTVA--/phone',
                    'spi:loctoservreq' => true,
                    'spi:personuid' => 251,
                    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/_TUFYVEVTVA--',
                    'spi:displayname' => 'Max Test',
                    'spi:plusgperareaauth' => false,
                    'spi:plusgiscertified' => false,
                    'spi:acceptingwfmail' => true,
                    'spi:locale_description' => 'English (United Kingdom)',
                    'spi:status_description' => 'Active',
                    'spi:statusiface' => false,
                ],
            3 =>
                [
                    'spi:nrcontractcomp' => 'NR',
                    'spi:wfmailelection_description' => 'Notify based on the process',
                    'spi:plusgsolnapprover' => false,
                    '_rowstamp' => '2860813230',
                    'spi:firstname' => 'Richard',
                    'spi:plusgtechauthority' => false,
                    'spi:city' => 'York',
                    'spi:primaryphone' => '07515614033',
                    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1/sms',
                    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1/email',
                    'spi:plusgauditapprover' => false,
                    'spi:plusgptwissuecounter' => 0,
                    'spi:phone' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3210991',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1/phone/0-64',
                                    'spi:phonenum' => '07515614033',
                                    'spi:phoneid' => 64,
                                    'rdf:about' => 'http://childkey#UEVSU09OL1BIT05FL1JMT05HNS8wNzUxNTYxNDAzMy9_TlVMTH4-',
                                ],
                        ],
                    'spi:lastname' => 'Long',
                    'spi:email' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '36451348',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1/email/0-26',
                                    'spi:emailaddress' => 'richard.long@uk.ibm.com',
                                    'spi:emailid' => 26,
                                    'rdf:about' => 'http://childkey#UEVSU09OL0VNQUlML3JpY2hhcmQubG9uZ0B1ay5pYm0uY29t',
                                ],
                        ],
                    'spi:language' => 'EN',
                    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1/phone',
                    'spi:loctoservreq' => true,
                    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/_UkxPTkc1',
                    'spi:displayname' => 'Richard Long',
                    'spi:title' => 'MR',
                    'spi:stateprovince' => 'N-Yorkshire',
                    'spi:locale_description' => 'English (United Kingdom)',
                    'spi:status_description' => 'Inactive',
                    'spi:statusiface' => false,
                    'spi:status' => 'INACTIVE',
                    'spi:country' => 'England',
                    'spi:locationorg' => 'NR',
                    'spi:driverpoints' => 0,
                    'spi:authtodrive' => false,
                    'spi:transemailelection' => 'NEVER',
                    'spi:addressline1' => '156 Holgate Road, Holgate',
                    'spi:plusgmocrevapp' => false,
                    'spi:locationsite' => 'NRFAMS',
                    'spi:department' => 'NDS Business Systems',
                    'spi:plusgfinauthority' => false,
                    'spi:driverarchived' => false,
                    'spi:nroid' => 'KRIGBY',
                    'spi:postalcode' => 'YO24 4EH',
                    'spi:personid' => 'RLONG5',
                    'spi:wfmailelection' => 'PROCESS',
                    'spi:plusgperissueauth' => false,
                    'spi:plusgperperfauth' => false,
                    'spi:statusdate' => '2018-07-12T07:19:18+01:00',
                    'spi:transemailelection_description' => 'Never Notify',
                    'spi:locale' => 'en_GB',
                    'spi:plusgrcfaapprover' => false,
                    'spi:plusgisospec' => false,
                    'spi:personuid' => 271,
                    'spi:plusgperareaauth' => false,
                    'spi:plusgiscertified' => false,
                    'spi:acceptingwfmail' => true,
                    'spi:primaryemail' => 'richard.long@uk.ibm.com',
                ],
            4 =>
                [
                    'spi:nrcontractcomp' => 'NR',
                    'spi:wfmailelection_description' => 'Notify based on the process',
                    'spi:plusgsolnapprover' => false,
                    'spi:supervisor' => 'ATHOMP18',
                    '_rowstamp' => '2860813231',
                    'spi:firstname' => 'Moyo',
                    'spi:plusgtechauthority' => false,
                    'spi:city' => 'Milton Keynes Central',
                    'spi:employeetype_description' => 'Employee',
                    'spi:primaryphone' => '01908 956766',
                    'spi:jobcode' => 'USER',
                    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--/sms',
                    'spi:jobcode_description' => 'User',
                    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--/email',
                    'spi:plusgauditapprover' => false,
                    'spi:plusgptwissuecounter' => 0,
                    'spi:phone' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '3212103',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--/phone/0-80',
                                    'spi:phonenum' => '01908 956766',
                                    'spi:phoneid' => 80,
                                    'rdf:about' => 'http://childkey#UEVSU09OL1BIT05FL01TQUxBTUkvMDE5MDggOTU2NzY2L35OVUxMfg--',
                                ],
                        ],
                    'spi:lastname' => 'Salami',
                    'spi:email' =>
                        [
                            0 =>
                                [
                                    'spi:isprimary' => true,
                                    'prefixes' =>
                                        [
                                            'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                            'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
                                            'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                                            'oslc' => 'http://open-services.net/ns/core#',
                                        ],
                                    '_rowstamp' => '194809213',
                                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--/email/0-42',
                                    'spi:emailaddress' => 'Moyo.Salami@networkrail.co.uk',
                                    'spi:emailid' => 42,
                                    'rdf:about' => 'http://childkey#UEVSU09OL0VNQUlML01veW8uU2FsYW1pQG5ldHdvcmtyYWlsLmNvLnVr',
                                ],
                        ],
                    'spi:language' => 'EN',
                    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--/phone',
                    'spi:loctoservreq' => true,
                    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/_TVNBTEFNSQ--',
                    'spi:displayname' => 'Moyo Salami',
                    'spi:title' => 'Mr',
                    'spi:stateprovince' => 'Buckinghamshire',
                    'spi:locale_description' => 'English (United Kingdom)',
                    'spi:status_description' => 'Inactive',
                    'spi:statusiface' => false,
                    'spi:employeetype' => 'EMPLOYEE',
                    'spi:status' => 'INACTIVE',
                    'spi:country' => 'England',
                    'spi:driverpoints' => 0,
                    'spi:authtodrive' => false,
                    'spi:transemailelection' => 'NEVER',
                    'spi:addressline1' => '500 Station Road, Elder Gate',
                    'spi:plusgmocrevapp' => false,
                    'spi:department' => 'Business Systems Support (Development)',
                    'spi:plusgfinauthority' => false,
                    'spi:driverarchived' => false,
                    'spi:postalcode' => 'MK9 1BB',
                    'spi:personid' => 'MSALAMI',
                    'spi:wfmailelection' => 'PROCESS',
                    'spi:plusgperissueauth' => false,
                    'spi:plusgperperfauth' => false,
                    'spi:statusdate' => '2018-07-12T07:19:24+01:00',
                    'spi:transemailelection_description' => 'Never Notify',
                    'spi:locale' => 'en_GB',
                    'spi:plusgrcfaapprover' => false,
                    'spi:plusgisospec' => false,
                    'spi:personuid' => 297,
                    'spi:plusgperareaauth' => false,
                    'spi:plusgiscertified' => false,
                    'spi:acceptingwfmail' => true,
                    'spi:primaryemail' => 'Moyo.Salami@networkrail.co.uk',
                ],
        ],
    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson',
];
