<?php

return [
    'member' => [
        0 => [
            'personuid' => 1191,
            'firstname' => 'Christopher',
            'plusgptwissuecounter' => 0,
            'plusgperperfauth' => false,
            'transemailelection_description' => 'Never Notify',
            'loctoservreq' => true,
            'brdacreatedby' => 'MAXIMO',
            'language' => 'EN',
            'plusgisospec' => false,
            'plusgsolnapprover' => false,
            'locale' => 'en_GB',
            'plusgiscertified' => false,
            'wfmailelection' => 'PROCESS',
            'employeetype_description' => 'Employee',
            '_rowstamp' => '2860813470',
            'plusgauditapprover' => false,
            'plusgmocrevapp' => false,
            'wfmailelection_description' => 'Notify based on the process',
            'personid' => 'CABEY',
            'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_Q0FCRVk-/sms',
            'href' => 'http://localhost/maximo/oslc/os/mxperson/_Q0FCRVk-',
            'department' => 'Business Systems Support (Development)',
            'email' => [
                0 => [
                    '_rowstamp' => '131475213',
                    'localref' => 'http://localhost/maximo/oslc/os/mxperson/_Q0FCRVk-/email/0-842',
                    'emailaddress' => 'christopher.abey@networkrail.co.uk',
                    'emailid' => 842,
                    'href' => 'http://childkey#UEVSU09OL0VNQUlML2NocmlzdG9waGVyLmFiZXlAbmV0d29ya3JhaWwuY28udWs-',
                    'isprimary' => true,
                ],
            ],
            'plusgrcfaapprover' => false,
            'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_Q0FCRVk-/email',
            'employeetype' => 'EMPLOYEE',
            'status_description' => 'Active',
            'driverarchived' => false,
            'plusgtechauthority' => false,
            'plusgperareaauth' => false,
            'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/_Q0FCRVk-/phone',
            'transemailelection' => 'NEVER',
            'authtodrive' => false,
            'lastname' => 'Abey',
            'statusdate' => '2011-12-14T14:30:56+00:00',
            'jobcode_description' => 'User',
            'nrcontractcomp' => 'NR',
            'statusiface' => false,
            'locale_description' => 'English (United Kingdom)',
            'acceptingwfmail' => true,
            'plusgfinauthority' => false,
            'displayname' => 'Christopher Abey',
            'jobcode' => 'USER',
            'driverpoints' => 0,
            'plusgperissueauth' => false,
            'primaryemail' => 'christopher.abey@networkrail.co.uk',
            'supervisor' => 'ATHOMP18',
            'status' => 'ACTIVE',
        ],
    ],
    'href' => 'http://localhost/maximo/oslc/os/mxperson',
    'responseInfo' => [
        'href' => 'http://localhost/maximo/oslc/os/mxperson?oslc.select=*&oslc.where=personid=%22cabey%22&lean=1&relativeuri=1',
    ],
];
