<?php

return [
    'spi:employeetype' => 'EMPLOYEE',
    'spi:status' => 'ACTIVE',
    'spi:driverpoints' => 0,
    'spi:authtodrive' => false,
    'spi:transemailelection' => 'NEVER',
    'spi:nrcontractcomp' => 'NR',
    'spi:plusgmocrevapp' => false,
    'spi:wfmailelection_description' => 'Notify based on the process',
    'spi:plusgsolnapprover' => false,
    'spi:supervisor' => 'ATHOMP18',
    'spi:department' => 'Business Systems Support (Development)',
    'spi:plusgfinauthority' => false,
    '_rowstamp' => '2860813470',
    'spi:firstname' => 'Christopher',
    'spi:plusgtechauthority' => false,
    'spi:driverarchived' => false,
    'spi:employeetype_description' => 'Employee',
    'spi:personid' => 'CABEY',
    'spi:wfmailelection' => 'PROCESS',
    'spi:jobcode' => 'USER',
    'sms_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/1191/sms',
    'spi:plusgperissueauth' => false,
    'spi:plusgperperfauth' => false,
    'spi:jobcode_description' => 'User',
    'spi:statusdate' => '2011-12-14T14:30:56+00:00',
    'spi:transemailelection_description' => 'Never Notify',
    'email_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/1191/email',
    'spi:locale' => 'en_GB',
    'spi:plusgauditapprover' => false,
    'spi:plusgrcfaapprover' => false,
    'spi:plusgisospec' => false,
    'spi:plusgptwissuecounter' => 0,
    'spi:lastname' => 'Abey',
    'spi:email' => [
        0 => [
            'spi:isprimary' => true,
            'prefixes' => [
                'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
                'oslc' => 'http://open-services.net/ns/core#',
            ],
            '_rowstamp' => '131475213',
            'localref' => 'http://localhost/maximo/oslc/os/mxperson/1191/email/0-842',
            'spi:emailaddress' => 'christopher.abey@networkrail.co.uk',
            'spi:emailid' => 842,
            'rdf:about' => 'http://childkey#UEVSU09OL0VNQUlML2NocmlzdG9waGVyLmFiZXlAbmV0d29ya3JhaWwuY28udWs-',
        ],
    ],
    'spi:language' => 'EN',
    'phone_collectionref' => 'http://localhost/maximo/oslc/os/mxperson/1191/phone',
    'spi:loctoservreq' => true,
    'spi:personuid' => 1191,
    'rdf:about' => 'http://localhost/maximo/oslc/os/mxperson/1191',
    'spi:displayname' => 'Christopher Abey',
    'spi:plusgperareaauth' => false,
    'prefixes' => [
        'rdf' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
        'spi' => 'http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#',
        'oslc' => 'http://open-services.net/ns/core#',
    ],
        'spi:plusgiscertified' => false,
        'spi:acceptingwfmail' => true,
        'spi:locale_description' => 'English (United Kingdom)',
        'spi:status_description' => 'Active',
        'spi:statusiface' => false,
        'spi:primaryemail' => 'christopher.abey@networkrail.co.uk',
    ];
